### ISSUE TITLE
64位木马运行的时候向c2请求payload返回404

### ISSUE THREAD

**Issue by furuanruan** [TryGoTry/DogCs4.4#11]
请教大佬：
利用profile文件自定义http-stager，可以发一个profile模板吗？
配置了C2 profile，但是不知道http-stager这里具体怎么写，set uri_x86 “***”，这里面的地址填写哪里呢

**Comment by furuanruan** [comment]
> 请教大佬： 利用profile文件自定义http-stager，可以发一个profile模板吗？ 配置了C2 profile，但是不知道http-stager这里具体怎么写，set uri_x86 “***”，这里面的地址填写哪里呢

问题发完，转头就解决了。。打扰了
http-stager {  
  set uri_x86 "/vue.min.js";
  set uri_x64 "/bootstrap-2.min.js";
}
任意填一下就行了。。。

**Comment by furuanruan** [comment]
刚测试winserver2012，使用https 443监听，32位和64位都无法上线。。。

**Comment by TryGoTry** [comment]
winserver2012原版cs是否可以正常上线.

**Comment by furuanruan** [comment]
> winserver2012原版cs是否可以正常上线.

刚试了一下也不行，我再排查一下原因，感谢回复
