### ISSUE TITLE
Cobalt Strike团队服务器不可用

### ISSUE THREAD

**Issue by xuwooyun** [TryGoTry/DogCs4.4#12]
连接错误?读取超时退出指定主机和端口上的Cobalt Strike团队服务器不可用。你必须先启动一个Cobalt Strike团队服务器。您想尝试其他连接吗?是(Y)否(N)

**Comment by TryGoTry** [comment]
没启动服务端。

**Comment by xuwooyun** [comment]
![image](https://user-images.githubusercontent.com/66466714/181274202-e464663f-214f-4c80-84bc-b7e8d2cbc849.png)
出现新问题 连接出错
