### ISSUE TITLE
切换输入法闪退，稳定复现

### ISSUE THREAD

**Issue by NickYan7** [TryGoTry/DogCs4.4#13]
Nice project!

然而发现一个闪退的情况：切换到其他 App，然后切换到中文输入法会闪退，或许是 Monterey 的原因？

```
$ java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

系统版本：macOS Monterey 12.4
```

![Screenshot2022-07-28 16 17 45](https://user-images.githubusercontent.com/27906343/181457337-2f177b03-532c-489a-8d2f-17d143ecb39d.jpg)

**Comment by TryGoTry** [comment]
从来没遇到过这个bug。。

**Comment by NickYan7** [comment]
https://bugs.openjdk.org/browse/JDK-8257242

似乎是 JAVA 的问题，寄了

**Comment by NickYan7** [comment]
用 Burp 自带的 JAVA 来调用，不再闪退了 😅
