### ISSUE TITLE
ssh 连接报错

### ISSUE THREAD

**Issue by NickYan7** [TryGOTry/DogCs4.4#18]
用了一段时间，很多功能很赞，非常喜欢！！🚀🚀

但是发现 DogCS 调用 `ssh` 和 `ssh-key` 连接 linux 机器有报错： `Could not connect to pipe: 2`
使用原版 CS 可正常连接，作者大大帮忙看看这个问题？感恩感恩 🙏

@TryGOTry

**Comment by TryGOTry** [comment]
不太清楚这个,基本上用不到这个功能，而且也没二改这个功能
