### ISSUE TITLE
师傅，运行teamserver 提示找不到server.teamserver类

### ISSUE THREAD

**Issue by XinChuanghe** [TryGOTry/DogCs4.4#23]
师傅，运行teamserver 提示找不到server.teamserver类，换了很多java环境，不清楚是什么问题

**Comment by TryGOTry** [comment]
自己的问题，仔细点自己发现

**Comment by ltfafei** [comment]
> 师傅，运行teamserver 提示找不到server.teamserver类，换了很多java环境，不清楚是什么问题

兄弟，咋就问问，解压密码多少？

**Comment by XinChuanghe** [comment]
> > 师傅，运行teamserver 提示找不到server.teamserver类，换了很多java环境，不清楚是什么问题
> 
> 兄弟，咋就问问，解压密码多少？

今天星期3呢
