### ISSUE TITLE
请问乱码如何修复

### ISSUE THREAD

**Issue by bytecaps** [TryGOTry/DogCs4.4#25]
![image](https://user-images.githubusercontent.com/52679771/192499692-398d1903-6699-45cf-bfdc-0bb33f315493.png)

**Comment by TryGOTry** [comment]
这不建议学一下英文

**Comment by bytecaps** [comment]
> 这不建议学一下英文

英文也乱码....

**Comment by bytecaps** [comment]
> > 这不建议学一下英文
> 
> 英文也乱码....

我是用原来的汉化版替换的jar包， 没用agent 还是乱码.

**Comment by TryGOTry** [comment]
不知道，其他人英文一切正常

**Comment by NickYan7** [comment]
-Dfile.encoding=UTF-8

**Comment by jhhd88** [comment]
中文也正常

**Comment by bytecaps** [comment]
解决了，彻底用原包，不要用替换， 之前汉化的整个文件夹都不用就没问题了。
