### ISSUE TITLE
关于Targets和文件浏览器显示问题的解决

### ISSUE THREAD

**Issue by D1sAbl4** [TryGOTry/DogCs4.4#28]
# Dogcs v2.3
## Targets 显示图标
![image](https://user-images.githubusercontent.com/51101413/196629310-9acab0db-0bec-43c7-933f-a3d4a71cb280.png)

## File Browser图标显示
![image](https://user-images.githubusercontent.com/51101413/196629967-d7b1ff8a-55c2-455b-bc85-004df94603a9.png)

# 在网上看到一篇修复文章https://mp.weixin.qq.com/s/ir98ehlXo9Mxp7Ub-IB6BQ

## 修复如下:
![image](https://user-images.githubusercontent.com/51101413/196630862-2c830863-cc16-414d-bc95-90819d4f736c.png)
---
![image](https://user-images.githubusercontent.com/51101413/196631067-3aa3f2fb-b2e4-4460-9863-f3be13b36044.png)

**Comment by TryGOTry** [comment]
谢谢关注，已更新v2.4修复.

**Comment by D1sAbl4** [comment]
# 不好意思哈 我发现File Browser在主题是白色的时候还有个问题, 在选中目录时目录名看不见
![image](https://user-images.githubusercontent.com/51101413/196656529-b2a86a06-5988-4aa0-b612-b3cb1dd0e1ee.png)

# 解决办法, 在选中目录的时候, 把前后颜色设成黑色
![image](https://user-images.githubusercontent.com/51101413/196656947-e53e223f-22cf-4d88-a778-945da3db529d.png)

![image](https://user-images.githubusercontent.com/51101413/196657090-d7bf6b6f-3d22-48fb-9618-51efa7ef8833.png)
